#spring.application.name=user-service

spring:
  application:
    name: user-service
#  config:
#    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
#spring:
#  cloud:
#    config:
#      uri: http://config-service:8888
#  config:
#    activate:
#      on-profile: dev


spring:
  cloud:
    config:
      import-check:
        enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081